apiVersion: v1
kind: Service
metadata:
  name: node-app
  namespace: testing
  labels:
    app: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - name: dns
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30001
